/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lXnXMxSMT3h
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { useState } from "react";
import {
  SelectItem,
  SelectLabel,
  Select,
  SelectTrigger,
  SelectContent,
  SelectGroup,
  SelectValue,
} from "@/components/ui/select";

export function WorkoutCard() {
  const [exercise, setExercise] = useState("");
  return (
    <>
      <Card>
        <CardHeader className="pb-0">
          <CardTitle>Exercise</CardTitle>
          <CardDescription>Select your exercise</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Select>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Select a fruit" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup className="">
                <SelectLabel>Fruits</SelectLabel>
                <SelectItem value="apple">Apple</SelectItem>
                <SelectItem value="banana">Banana</SelectItem>
                <SelectItem value="blueberry">Blueberry</SelectItem>
                <SelectItem value="grapes">Grapes</SelectItem>
                <SelectItem value="pineapple">Pineapple</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
        </CardContent>
      </Card>
      <Card className="w-full max-w-sm">
        <CardHeader className="pb-0">
          <CardTitle>Repetitions</CardTitle>
          <CardDescription>Enter the number of repetitions</CardDescription>
        </CardHeader>
        <CardContent className="flex items-center space-x-4">
          <Label className="sr-only" htmlFor="repetitions">
            Repetitions
          </Label>
          <Input
            className="w-12 text-center"
            id="repetitions"
            placeholder="10"
          />
        </CardContent>
      </Card>
    </>
  );
}
